/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ems.pl;

import java.awt.Container;
import java.awt.Toolkit;

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public static Container c;
    private int empId;
    private String empType;
    
    public MainFrame(int empId,String empType) {
        initComponents();
        c=getContentPane();
        
        this.empId=empId;
        this.empType=empType;
        
        if(this.empType.equalsIgnoreCase("employee"))
        {
        menubar.remove(mnuems);
        menubar.remove(mnureports);
        }
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menubar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuems = new javax.swing.JMenu();
        miManage = new javax.swing.JMenuItem();
        mnureports = new javax.swing.JMenu();
        miEmpReports = new javax.swing.JMenuItem();
        mnuprofile = new javax.swing.JMenu();
        mimanageprofile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        menubar.add(mnuFile);

        mnuems.setText("EMS");

        miManage.setText("Manage Employee");
        miManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageActionPerformed(evt);
            }
        });
        mnuems.add(miManage);

        menubar.add(mnuems);

        mnureports.setText("Reports");

        miEmpReports.setText("EmpReports");
        mnureports.add(miEmpReports);

        menubar.add(mnureports);

        mnuprofile.setText("Profile");

        mimanageprofile.setText("Manage Profile");
        mimanageprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mimanageprofileActionPerformed(evt);
            }
        });
        mnuprofile.add(mimanageprofile);

        menubar.add(mnuprofile);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed


        LoginFrame log=new LoginFrame();
        log.setVisible(true);
        this.dispose();
        

        // TODO add your handling code here:
    }//GEN-LAST:event_miLogoutActionPerformed

    private void mimanageprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mimanageprofileActionPerformed

        c.removeAll();
        c.setVisible(false);
        ManagePanel objmp=new ManagePanel(empId);
        objmp.setBounds(30, 30, 660, 720);
        c.add(objmp);
        c.setVisible(true);
        
        
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_mimanageprofileActionPerformed

    private void miManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageActionPerformed


        c.removeAll();
        c.setVisible(false);
        EmployeePanel objemp=new EmployeePanel();
        objemp.setBounds(30, 30, 660, 720);
        c.add(objemp);
        c.setVisible(true);
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_miManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem miEmpReports;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miManage;
    private javax.swing.JMenuItem mimanageprofile;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuems;
    private javax.swing.JMenu mnuprofile;
    private javax.swing.JMenu mnureports;
    // End of variables declaration//GEN-END:variables
}
